In [23]:
import pandas as pd

df = pd.read_csv(r"C:/Users/User/Downloads/LPI_TML.csv")

df.head()

,STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,...,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0,datastructure,WB.DATA360:DS_DATA360(1.2),I,A2,DEU,LPI_TML,_Z,_Z,_Z,SCORE,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Two,Logistics Performance Index (LPI),CCYY,Units,Normal value,Public
1,datastructure,WB.DATA360:DS_DATA360(1.2),I,A2,SWE,LPI_TML,_Z,_Z,_Z,SCORE,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Two,Logistics Performance Index (LPI),CCYY,Units,Normal value,Public
2,datastructure,WB.DATA360:DS_DATA360(1.2),I,A2,BEL,LPI_TML,_Z,_Z,_Z,SCORE,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Two,Logistics Performance Index (LPI),CCYY,Units,Normal value,Public
3,datastructure,WB.DATA360:DS_DATA360(1.2),I,A2,AUT,LPI_TML,_Z,_Z,_Z,SCORE,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Two,Logistics Performance Index (LPI),CCYY,Units,Normal value,Public
4,datastructure,WB.DATA360:DS_DATA360(1.2),I,A2,JPN,LPI_TML,_Z,_Z,_Z,SCORE,...,Not Applicable,Not Applicable,Not Applicable,Number (real number),Two,Logistics Performance Index (LPI),CCYY,Units,Normal value,Public

In [21]:
df.shape

(2158, 41)

In [25]:
df.columns

Index(['STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'REF_AREA', 'INDICATOR',
       'SEX', 'AGE', 'URBANISATION', 'UNIT_MEASURE', 'COMP_BREAKDOWN_1',
       'COMP_BREAKDOWN_2', 'COMP_BREAKDOWN_3', 'TIME_PERIOD', 'AGG_METHOD',
       'UNIT_TYPE', 'DECIMALS', 'DATABASE_ID', 'TIME_FORMAT', 'UNIT_MULT',
       'OBS_CONF', 'OBS_VALUE', 'OBS_STATUS', 'FREQ_LABEL', 'REF_AREA_LABEL',
       'INDICATOR_LABEL', 'SEX_LABEL', 'AGE_LABEL', 'URBANISATION_LABEL',
       'UNIT_MEASURE_LABEL', 'COMP_BREAKDOWN_1_LABEL',
       'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_3_LABEL', 'AGG_METHOD_LABEL',
       'UNIT_TYPE_LABEL', 'DECIMALS_LABEL', 'DATABASE_ID_LABEL',
       'TIME_FORMAT_LABEL', 'UNIT_MULT_LABEL', 'OBS_STATUS_LABEL',
       'OBS_CONF_LABEL'],
      dtype='object')

In [27]:
clean_df = df[["REF_AREA_LABEL", "TIME_PERIOD", "OBS_VALUE"]]

clean_df.head()

  REF_AREA_LABEL  TIME_PERIOD  OBS_VALUE
0        Germany         2018   4.392114
1         Sweden         2018   4.284866
2        Belgium         2018   4.410293
3        Austria         2018   4.250803
4          Japan         2018   4.254069

In [29]:
clean_df = clean_df.rename(columns={
    "REF_AREA_LABEL": "Country",
    "TIME_PERIOD": "Year",
    "OBS_VALUE": "LPI_Score"
})

clean_df.head()

   Country  Year  LPI_Score
0  Germany  2018   4.392114
1   Sweden  2018   4.284866
2  Belgium  2018   4.410293
3  Austria  2018   4.250803
4    Japan  2018   4.254069

In [31]:
clean_df.isnull().sum()

Country      0
Year         0
LPI_Score    0
dtype: int64

In [33]:
clean_df = clean_df.rename(columns={
    "REF_AREA_LABEL": "Country",
    "TIME_PERIOD": "Year",
    "OBS_VALUE": "LPI_Score"
})

# Remove commas from country names
clean_df["Country"] = clean_df["Country"].str.replace(",", "")

In [35]:
#clean data
clean_df = clean_df.dropna()

clean_df.shape

(2158, 3)

In [37]:
#save clean csv

clean_df.to_csv("cleaned_LPI_data.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.